# Generated by Django 2.1 on 2020-05-30 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 14, 9, 8, 578446, tzinfo=utc)),
        ),
    ]
